# config/packages/framework.yaml
# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Protection CSRF activée pour les formulaires
    form:
        csrf_protection: true

    # PropertyInfo component
    property_info:
        enabled: true

    # Session : ne démarre que si vous lisez ou écrivez
    session:
        enabled: true

    # ESI et fragments si nécessaire
    # esi: true
    # fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
