twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'form_div_layout.html.twig'  # ✅ thème par défaut de Symfony



when@test:
    twig:
        strict_variables: true
